version: '3.8'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    volumes:
      - .:/app
      - ./htmlcov:/app/htmlcov
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    working_dir: /app
    entrypoint: ["pytest", "--cov=cluedo_game", "--cov-report=term-missing", "--cov-report=html", "-v"]
